services:
  metadata:
    build:
      context: .
    container_name: metadata
    restart: unless-stopped
    volumes:
      - ../inbox:/inbox
    environment:
      - INBOX_DIR=/inbox
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.1'
    networks:
      - honeypot

networks:
  honeypot:
    driver: bridge
