# First deploy to a fresh server (port 22, before setup.sh hardens the host).
# For honeypots: assembles a docker-compose.yml via include: and concatenates setup fragments.
# For backends: copies the deploy/ folder as-is.
# After first deploy completes, use redeploy.ps1 for all subsequent updates.

param(
    [string]$Server,
    [switch]$h,
    [switch]$Help
)

$manifest  = Join-Path $PSScriptRoot "honey-net.json"
$stateFile = Join-Path $PSScriptRoot "state.json"

if (-not (Test-Path $manifest)) { Write-Error "honey-net.json not found."; exit 1 }
$servers = Get-Content $manifest | ConvertFrom-Json

if ($h -or $Help) {
    $serverBlock = ($servers | ForEach-Object {
        $ports = if ($_.ports.Count) { $_.ports -join ", " } else { "none" }
        $hps   = if ($_.honeypots.Count) { $_.honeypots -join ", " } else { "-" }
        "  {0,-25} type={1,-10} ports={2,-12} honeypots={3}" -f $_.name, $_.type, $ports, $hps
    }) -join "`n"

    Write-Host @"
deploy.ps1 [-Server <name>] [-h]

First deploy only. The server must be reachable on port 22 (before setup.sh runs).
Copies the deployment package to the server and prints instructions to run setup.sh.

After setup.sh completes, port 22 is closed and SSH moves to port 65022 (Tailscale only).
Use redeploy.ps1 for all subsequent updates.

HONEYPOT ASSEMBLY
  Generates a docker-compose.yml using the Docker Compose include: directive, one entry
  per honeypot package. Concatenates server-config/setup.sh with each honeypot's
  setup/fragment.sh into a single setup.sh on the server.

BACKEND DEPLOY
  Copies the backend's deploy/ folder directly. The .env file is excluded — it is
  generated by setup.sh at provisioning time.

SERVERS (from honey-net.json)
$serverBlock

REQUIRES
  state.json with public_ip entries (run sync-ips.ps1 after terraform apply)
"@
    exit 0
}

# Load state
if (-not (Test-Path $stateFile)) {
    Write-Error "state.json not found. Run sync-ips.ps1 after terraform apply."
    exit 1
}
$state = Get-Content $stateFile | ConvertFrom-Json

# Server selection
if (-not $Server) {
    Write-Host ""
    Write-Host "Select a server to deploy:"
    $i = 0
    foreach ($s in $servers) {
        $ip    = if ($state.PSObject.Properties[$s.name]) { $state.$($s.name).public_ip } else { $null }
        $ipStr = if ($ip) { $ip } else { "(no IP — run sync-ips.ps1)" }
        $ports = if ($s.ports.Count) { $s.ports -join "," } else { "none" }
        Write-Host ("  [{0}] {1,-25} type={2,-10} ports={3,-10} ip={4}" -f $i, $s.name, $s.type, $ports, $ipStr)
        $i++
    }
    Write-Host ""
    $choice = Read-Host "Enter number"
    if ($choice -notmatch '^\d+$' -or [int]$choice -ge $servers.Count) {
        Write-Error "Invalid selection."
        exit 1
    }
    $serverDef = $servers[[int]$choice]
} else {
    $serverDef = $servers | Where-Object { $_.name -eq $Server }
    if (-not $serverDef) {
        Write-Error "Server '$Server' not found in honey-net.json."
        exit 1
    }
}

$name     = $serverDef.name
$sshKey   = ($serverDef.ssh_key -replace "^~", $env:USERPROFILE)
$publicIp = if ($state.PSObject.Properties[$name]) { $state.$name.public_ip } else { $null }

if ([string]::IsNullOrWhiteSpace($publicIp)) {
    Write-Error "No public IP for '$name' in state.json. Run sync-ips.ps1."
    exit 1
}

$remote  = "root@${publicIp}"
$tempDir = Join-Path $env:TEMP "honey-net-deploy-$(Get-Random)"

try {
    New-Item -ItemType Directory -Path $tempDir | Out-Null
    $pkgDir = Join-Path $tempDir $name

    if ($serverDef.type -eq "backend") {
        $src = Join-Path $PSScriptRoot "$name\deploy"
        if (-not (Test-Path $src)) {
            Write-Error "Backend deploy folder not found: $src"
            exit 1
        }
        Write-Host "Staging $name (backend)..."
        robocopy $src $pkgDir /E /XF ".env" | Out-Null
        if ($LASTEXITCODE -ge 8) { Write-Error "Staging failed (robocopy exit $LASTEXITCODE)."; exit 1 }

    } elseif ($serverDef.type -eq "honeypot") {
        Write-Host "Assembling deploy package for $name..."
        New-Item -ItemType Directory -Path $pkgDir | Out-Null

        # Generate docker-compose.yml with include: entries
        $includePaths = $serverDef.honeypots | ForEach-Object { "  - path: $_/docker-compose.yml" }
        @"
# Generated by deploy.ps1 — do not edit on the server.
# Source of truth: honey-net.json (honeypots field) and honey-pots/<name>/deploy/
include:
$($includePaths -join "`n")
"@ | Set-Content (Join-Path $pkgDir "docker-compose.yml") -Encoding UTF8

        # Copy server-config conf files alongside setup.sh so it can reference them via $SCRIPT_DIR
        $confFiles = @("sshd_hardening.conf", "99-hardening.conf", "fail2ban-jail.local")
        foreach ($cf in $confFiles) {
            $src = Join-Path $PSScriptRoot "server-config\$cf"
            if (-not (Test-Path $src)) { Write-Error "server-config/$cf not found."; exit 1 }
            Copy-Item $src (Join-Path $pkgDir $cf)
        }

        # Copy each honeypot's deploy/ folder
        foreach ($hp in $serverDef.honeypots) {
            $hpSrc = Join-Path $PSScriptRoot "honey-pots\$hp\deploy"
            if (-not (Test-Path $hpSrc)) {
                Write-Error "Honeypot deploy folder not found: $hpSrc"
                exit 1
            }
            $hpDst = Join-Path $pkgDir $hp
            robocopy $hpSrc $hpDst /E /XF ".env" | Out-Null
            if ($LASTEXITCODE -ge 8) { Write-Error "Failed to stage $hp (robocopy exit $LASTEXITCODE)."; exit 1 }
        }

        # Concatenate server-config/setup.sh + each honeypot's fragment.sh
        $baseSh = Join-Path $PSScriptRoot "server-config\setup.sh"
        if (-not (Test-Path $baseSh)) {
            Write-Error "server-config/setup.sh not found."
            exit 1
        }
        $setupContent = Get-Content $baseSh -Raw

        foreach ($hp in $serverDef.honeypots) {
            $fragment = Join-Path $PSScriptRoot "honey-pots\$hp\deploy\setup\fragment.sh"
            if (Test-Path $fragment) {
                $setupContent += "`n`n# --- $hp ---`n"
                $setupContent += Get-Content $fragment -Raw
            } else {
                Write-Warning "No fragment.sh for honeypot '$hp' at $fragment — skipping."
            }
        }
        $setupContent | Set-Content (Join-Path $pkgDir "setup.sh") -Encoding UTF8 -NoNewline

    } else {
        Write-Error "Unknown server type '$($serverDef.type)' for '$name'."
        exit 1
    }

    # SCP package to server
    Write-Host "Copying to ${remote} (port 22)..."
    scp -r -P 22 -i $sshKey `
        -o StrictHostKeyChecking=no `
        -o UserKnownHostsFile=NUL `
        $pkgDir "${remote}:/root/"
    if ($LASTEXITCODE -ne 0) { Write-Error "Transfer failed (scp exit $LASTEXITCODE)."; exit 1 }

} finally {
    Remove-Item -Recurse -Force $tempDir -ErrorAction SilentlyContinue
}

Write-Host ""
Write-Host "Deployed to /root/$name on $publicIp"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Verify your SSH key is in ~/.ssh/authorized_keys on the server"
Write-Host "     (setup.sh will disable password auth — if your key is not there you will be locked out)"
Write-Host ""
Write-Host "  2. SSH in:"
Write-Host "     ssh -i $sshKey -p 22 root@$publicIp"
Write-Host ""
Write-Host "  3. Run setup:"
Write-Host "     sudo bash /root/$name/setup.sh"
Write-Host ""
Write-Host "  After setup completes, port 22 is closed. SSH moves to port 65022 (Tailscale only)."
Write-Host "  Run sync-ips.ps1 to capture the Tailscale IP, then use redeploy.ps1 for future updates."
