# Updates a live server over Tailscale (port 65022). Does not touch system configuration.
# Copies updated service files and runs docker compose up --build.
# Use deploy.ps1 for first-time provisioning of a fresh server.

param(
    [string]$Server,
    [switch]$h,
    [switch]$Help
)

$manifest  = Join-Path $PSScriptRoot "honey-net.json"
$stateFile = Join-Path $PSScriptRoot "state.json"

if (-not (Test-Path $manifest)) { Write-Error "honey-net.json not found."; exit 1 }
$servers = Get-Content $manifest | ConvertFrom-Json

if ($h -or $Help) {
    $serverBlock = ($servers | ForEach-Object {
        $ports = if ($_.ports.Count) { $_.ports -join ", " } else { "none" }
        $hps   = if ($_.honeypots.Count) { $_.honeypots -join ", " } else { "-" }
        "  {0,-25} type={1,-10} ports={2,-12} honeypots={3}" -f $_.name, $_.type, $ports, $hps
    }) -join "`n"

    Write-Host @"
redeploy.ps1 [-Server <name>] [-h]

Updates a live server via Tailscale (port 65022). The server must have already been
provisioned with deploy.ps1 and setup.sh. Does not touch system configuration (UFW,
sshd, fail2ban, Tailscale) — only updates service files and restarts the stack.

For honeypots: regenerates docker-compose.yml and copies updated honeypot service files,
then runs docker compose up --build -d.

For backends: copies updated deploy/ folder (excluding .env) and runs docker compose up -d.

SERVERS (from honey-net.json)
$serverBlock

REQUIRES
  Tailscale running locally
  state.json with tailscale_ip entries (run sync-ips.ps1 after servers join Tailscale)
"@
    exit 0
}

# Load state
if (-not (Test-Path $stateFile)) {
    Write-Error "state.json not found. Run sync-ips.ps1."
    exit 1
}
$state = Get-Content $stateFile | ConvertFrom-Json

# Server selection
if (-not $Server) {
    Write-Host ""
    Write-Host "Select a server to redeploy:"
    $i = 0
    foreach ($s in $servers) {
        $tsIp  = if ($state.PSObject.Properties[$s.name]) { $state.$($s.name).tailscale_ip } else { $null }
        $ipStr = if ($tsIp) { $tsIp } else { "(no Tailscale IP — run sync-ips.ps1)" }
        $ports = if ($s.ports.Count) { $s.ports -join "," } else { "none" }
        Write-Host ("  [{0}] {1,-25} type={2,-10} ports={3,-10} tailscale={4}" -f $i, $s.name, $s.type, $ports, $ipStr)
        $i++
    }
    Write-Host ""
    $choice = Read-Host "Enter number"
    if ($choice -notmatch '^\d+$' -or [int]$choice -ge $servers.Count) {
        Write-Error "Invalid selection."
        exit 1
    }
    $serverDef = $servers[[int]$choice]
} else {
    $serverDef = $servers | Where-Object { $_.name -eq $Server }
    if (-not $serverDef) {
        Write-Error "Server '$Server' not found in honey-net.json."
        exit 1
    }
}

$name        = $serverDef.name
$sshKey      = ($serverDef.ssh_key -replace "^~", $env:USERPROFILE)
$tailscaleIp = if ($state.PSObject.Properties[$name]) { $state.$name.tailscale_ip } else { $null }

if ([string]::IsNullOrWhiteSpace($tailscaleIp)) {
    Write-Error "No Tailscale IP for '$name' in state.json. Run sync-ips.ps1 (Tailscale must be active)."
    exit 1
}

$remote  = "root@${tailscaleIp}"
$sshArgs = @("-i", $sshKey, "-p", "65022", "-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=NUL")
$tempDir = Join-Path $env:TEMP "honey-net-redeploy-$(Get-Random)"

try {
    New-Item -ItemType Directory -Path $tempDir | Out-Null
    $pkgDir = Join-Path $tempDir $name

    if ($serverDef.type -eq "backend") {
        $src = Join-Path $PSScriptRoot "$name\deploy"
        if (-not (Test-Path $src)) {
            Write-Error "Backend deploy folder not found: $src"
            exit 1
        }
        Write-Host "Staging $name (backend)..."
        robocopy $src $pkgDir /E /XF ".env" | Out-Null
        if ($LASTEXITCODE -ge 8) { Write-Error "Staging failed (robocopy exit $LASTEXITCODE)."; exit 1 }

    } elseif ($serverDef.type -eq "honeypot") {
        Write-Host "Assembling updated package for $name..."
        New-Item -ItemType Directory -Path $pkgDir | Out-Null

        # Regenerate docker-compose.yml
        $includePaths = $serverDef.honeypots | ForEach-Object { "  - path: $_/docker-compose.yml" }
        @"
# Generated by redeploy.ps1 — do not edit on the server.
# Source of truth: honey-net.json (honeypots field) and honey-pots/<name>/deploy/
include:
$($includePaths -join "`n")
"@ | Set-Content (Join-Path $pkgDir "docker-compose.yml") -Encoding UTF8

        # Copy updated honeypot service folders
        foreach ($hp in $serverDef.honeypots) {
            $hpSrc = Join-Path $PSScriptRoot "honey-pots\$hp\deploy"
            if (-not (Test-Path $hpSrc)) {
                Write-Error "Honeypot deploy folder not found: $hpSrc"
                exit 1
            }
            $hpDst = Join-Path $pkgDir $hp
            robocopy $hpSrc $hpDst /E /XF ".env" | Out-Null
            if ($LASTEXITCODE -ge 8) { Write-Error "Failed to stage $hp (robocopy exit $LASTEXITCODE)."; exit 1 }
        }

    } else {
        Write-Error "Unknown server type '$($serverDef.type)' for '$name'."
        exit 1
    }

    # SCP to server via Tailscale
    Write-Host "Copying to ${remote} (port 65022)..."
    scp -r -P 65022 -i $sshKey `
        -o StrictHostKeyChecking=no `
        -o UserKnownHostsFile=NUL `
        $pkgDir "${remote}:/root/"
    if ($LASTEXITCODE -ne 0) { Write-Error "Transfer failed (scp exit $LASTEXITCODE)."; exit 1 }

    # Sync files from /root/ to /opt/ and restart stack
    Write-Host "Restarting stack on $name..."
    if ($serverDef.type -eq "honeypot") {
        $restartCmd = "rsync -a --delete --exclude='.env' /root/$name/ /opt/$name/ && docker compose -f /opt/$name/docker-compose.yml up --build -d"
    } else {
        $restartCmd = "rsync -a --delete --exclude='.env' /root/$name/ /opt/$name/ && docker compose -f /opt/$name/docker-compose.yml up -d"
    }
    ssh @sshArgs "${remote}" $restartCmd
    if ($LASTEXITCODE -ne 0) { Write-Error "Stack restart failed."; exit 1 }

} finally {
    Remove-Item -Recurse -Force $tempDir -ErrorAction SilentlyContinue
}

Write-Host ""
Write-Host "$name redeployed successfully."
